Order:
  modifiers:
    - GSTTaxModifier

OrderModifier_Descriptor:
  extensions:
    - GSTTaxDecorator

Product:
  extensions:
    - GSTTaxDecorator

---
Only:
  moduleexists: 'ProductVariation'
---
ProductVariation:
  extensions:
    - GSTTaxDecorator
---


StoreAdmin:
  managed_models:
    - GSTTaxModifierOptions
