OrderModifier_Descriptor:
  extensions:
    - GSTTaxDecorator

Product:
  extensions:
    - GSTTaxDecorator

---
Only:
  classexists: 'ProductVariation'
---
ProductVariation:
  extensions:
    - GSTTaxDecorator
---


StoreAdmin:
  managed_models:
    - GSTTaxModifierOptions
